
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

namespace  Billmanager.Translations.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;

        private static Assembly assembly = typeof(Resources).GetTypeInfo().Assembly;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {            
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Billmanager.Translations.Texts.Resources", assembly);
                    resourceMan = temp;
                    resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;
                }
                return resourceMan;
            }
            set {
                resourceMan = value;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
                resourceMan = null;
            }
        }
        /// <summary>Looks up a localized string similar to Address.</summary>
        public static string Address => ResourceManager.GetString("Address", resourceCulture);       
        /// <summary>Looks up a localized string similar to Addresscard.</summary>
        public static string Addresscard => ResourceManager.GetString("Addresscard", resourceCulture);       
        /// <summary>Looks up a localized string similar to Bill.</summary>
        public static string Bill => ResourceManager.GetString("Bill", resourceCulture);       
        /// <summary>Looks up a localized string similar to Billmanager.</summary>
        public static string Billmanager => ResourceManager.GetString("Billmanager", resourceCulture);       
        /// <summary>Looks up a localized string similar to Cancel.</summary>
        public static string Cancel => ResourceManager.GetString("Cancel", resourceCulture);       
        /// <summary>Looks up a localized string similar to CarDocuments.</summary>
        public static string CarDocuments => ResourceManager.GetString("CarDocuments", resourceCulture);       
        /// <summary>Looks up a localized string similar to CarInformation.</summary>
        public static string CarInformation => ResourceManager.GetString("CarInformation", resourceCulture);       
        /// <summary>Looks up a localized string similar to CarMake.</summary>
        public static string CarMake => ResourceManager.GetString("CarMake", resourceCulture);       
        /// <summary>Looks up a localized string similar to ChassisNo.</summary>
        public static string ChassisNo => ResourceManager.GetString("ChassisNo", resourceCulture);       
        /// <summary>Looks up a localized string similar to CreateAddresscard.</summary>
        public static string CreateAddresscard => ResourceManager.GetString("CreateAddresscard", resourceCulture);       
        /// <summary>Looks up a localized string similar to CreateBill.</summary>
        public static string CreateBill => ResourceManager.GetString("CreateBill", resourceCulture);       
        /// <summary>Looks up a localized string similar to CreateCar.</summary>
        public static string CreateCar => ResourceManager.GetString("CreateCar", resourceCulture);       
        /// <summary>Looks up a localized string similar to CreateCustomer.</summary>
        public static string CreateCustomer => ResourceManager.GetString("CreateCustomer", resourceCulture);       
        /// <summary>Looks up a localized string similar to CreateOffer.</summary>
        public static string CreateOffer => ResourceManager.GetString("CreateOffer", resourceCulture);       
        /// <summary>Looks up a localized string similar to CreateWorkcard.</summary>
        public static string CreateWorkcard => ResourceManager.GetString("CreateWorkcard", resourceCulture);       
        /// <summary>Looks up a localized string similar to Cubic.</summary>
        public static string Cubic => ResourceManager.GetString("Cubic", resourceCulture);       
        /// <summary>Looks up a localized string similar to Customer.</summary>
        public static string Customer => ResourceManager.GetString("Customer", resourceCulture);       
        /// <summary>Looks up a localized string similar to Edit.</summary>
        public static string Edit => ResourceManager.GetString("Edit", resourceCulture);       
        /// <summary>Looks up a localized string similar to EngineNo.</summary>
        public static string EngineNo => ResourceManager.GetString("EngineNo", resourceCulture);       
        /// <summary>Looks up a localized string similar to Expected_culture_identifier.</summary>
        public static string Expected_culture_identifier => ResourceManager.GetString("Expected_culture_identifier", resourceCulture);       
        /// <summary>Looks up a localized string similar to Firstname.</summary>
        public static string Firstname => ResourceManager.GetString("Firstname", resourceCulture);       
        /// <summary>Looks up a localized string similar to FirstOnMarket.</summary>
        public static string FirstOnMarket => ResourceManager.GetString("FirstOnMarket", resourceCulture);       
        /// <summary>Looks up a localized string similar to Location.</summary>
        public static string Location => ResourceManager.GetString("Location", resourceCulture);       
        /// <summary>Looks up a localized string similar to Name.</summary>
        public static string Name => ResourceManager.GetString("Name", resourceCulture);       
        /// <summary>Looks up a localized string similar to New.</summary>
        public static string New => ResourceManager.GetString("New", resourceCulture);       
        /// <summary>Looks up a localized string similar to Overview.</summary>
        public static string Overview => ResourceManager.GetString("Overview", resourceCulture);       
        /// <summary>Looks up a localized string similar to Phone.</summary>
        public static string Phone => ResourceManager.GetString("Phone", resourceCulture);       
        /// <summary>Looks up a localized string similar to Plate.</summary>
        public static string Plate => ResourceManager.GetString("Plate", resourceCulture);       
        /// <summary>Looks up a localized string similar to Print.</summary>
        public static string Print => ResourceManager.GetString("Print", resourceCulture);       
        /// <summary>Looks up a localized string similar to Remark.</summary>
        public static string Remark => ResourceManager.GetString("Remark", resourceCulture);       
        /// <summary>Looks up a localized string similar to RootNumber.</summary>
        public static string RootNumber => ResourceManager.GetString("RootNumber", resourceCulture);       
        /// <summary>Looks up a localized string similar to Save.</summary>
        public static string Save => ResourceManager.GetString("Save", resourceCulture);       
        /// <summary>Looks up a localized string similar to Titel_Customer.</summary>
        public static string Titel_Customer => ResourceManager.GetString("Titel_Customer", resourceCulture);       
        /// <summary>Looks up a localized string similar to Typ.</summary>
        public static string Typ => ResourceManager.GetString("Typ", resourceCulture);       
        /// <summary>Looks up a localized string similar to Typecertificate.</summary>
        public static string Typecertificate => ResourceManager.GetString("Typecertificate", resourceCulture);       
        /// <summary>Looks up a localized string similar to Workcard.</summary>
        public static string Workcard => ResourceManager.GetString("Workcard", resourceCulture);       
        /// <summary>Looks up a localized string similar to ZipCode.</summary>
        public static string ZipCode => ResourceManager.GetString("ZipCode", resourceCulture);       
    }
}
  